### ISSUE TITLE
PRs welcome?

### ISSUE THREAD

**Issue by cwinters8** [sagikazarmark/temporal-intro-workshop#10]
Hey, this is a really great resource and I'm learning a lot with it. Just curious if you'd like PRs? Seems like there have been some changes since last year and it might be cool to keep this up to date for other folks to reference.

I haven't been through everything yet but one thing I've noticed is that the [`client.NewClient()`](https://github.com/sagikazarmark/temporal-intro-workshop/blob/master/cmd/worker/main.go#L24) is now deprecated, in favor of either `client.Dial()` or `client.NewLazyClient()`, according to [package docs](https://pkg.go.dev/go.temporal.io/sdk/client#NewClient).

Happy to contribute if the value/desire is there.

Cheers!

**Comment by sagikazarmark** [comment]
Thanks for reaching out @cwinters8 !

PRs are always welcome and appreciated.

It might also make sense to do some upgrades (eg. upgrade temporal and postgres in docker compose), if you are up for it.

In any case, any contribution is welcome and appreciated.

Thanks!

**Comment by sagikazarmark** [comment]
This should be done
